"use client";

import Link from "next/link";
import { useState } from "react";
import { FlowFrame } from "@/components/layout/flow-frame";
import { Icon } from "@/components/ui/icon";
import { CARE_TOPICS, LIBRARY_ITEMS, ROADMAP_STEPS } from "./fixtures";

type CareView = "welcome" | "mode" | "free" | "free-result" | "dashboard" | "roadmap" | "library" | "companion";

export function CareGuideFlow() {
  const [view, setView] = useState<CareView>("welcome");
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("All");
  const [companion, setCompanion] = useState("");

  function goBack() {
    if (view === "welcome") return window.history.back();
    if (view === "mode") return setView("welcome");
    if (view === "free" || view === "dashboard") return setView("mode");
    if (view === "free-result") return setView("free");
    return setView("dashboard");
  }

  const title = view === "free" || view === "free-result" ? "Free consultation" : view === "roadmap" ? "Your care roadmap" : view === "library" ? "Health library" : view === "companion" ? "Daily companion" : "Care Guide";
  const subtitle = view === "free" || view === "free-result" ? "Powered by 3 AI brains" : "Personalized for your case";

  return <FlowFrame className="care-guide-frame"><main className="flow-shell care-guide-shell"><header className="flow-header"><div className="flow-header-row"><button className="icon-button" onClick={goBack} aria-label="Go back"><Icon name="arrow-left" size={18} /></button><div><h1>{title}</h1><p>{subtitle}</p></div></div></header>
    {view === "welcome" && <section className="care-welcome"><div className="care-hero-mark"><Icon name="book" size={27} /><span><Icon name="sparkles" size={12} /></span></div><p className="eyebrow">Your next step, made clearer</p><h1>Care that keeps moving <em>with you.</em></h1><p>Turn a health question or recent assessment into a simple path forward.</p><div className="care-preview"><div><span><Icon name="check" size={12} /></span><p><strong>Know what comes next</strong><small>A practical roadmap around your case.</small></p></div><div><span><Icon name="book" size={12} /></span><p><strong>Learn at your pace</strong><small>Short, curated health resources.</small></p></div><div><span><Icon name="message" size={12} /></span><p><strong>Check in anytime</strong><small>A calm companion for everyday questions.</small></p></div></div><button className="button primary wide" onClick={() => setView("mode")}>Open Care Guide <Icon name="chevron-right" size={15} /></button><small className="standalone-disclaimer">Educational support · Not medical advice</small></section>}
    {view === "mode" && <section className="flow-body care-mode"><h2>How would you like to <em>use Care Guide</em>?</h2><p>Two ways to get help — choose what fits your moment.</p><div className="care-mode-list"><button className="featured" onClick={() => setView("dashboard")}><span><Icon name="check" size={19} /></span><span><strong>Based on your pre-triage</strong><small>A roadmap, library and companion built around your latest assessment.</small></span><b>Recommended</b><Icon name="chevron-right" size={15} /></button><button onClick={() => setView("free")}><span><Icon name="sparkles" size={19} /></span><span><strong>Free consultation</strong><small>Ask a general health question to three demo AI perspectives.</small></span><Icon name="chevron-right" size={15} /></button></div><div className="care-safety"><Icon name="shield" size={14} />Your care text is not cached for offline access.</div></section>}
    {view === "free" && <section className="flow-body care-free"><div className="care-flow-hero"><p><Icon name="sparkles" size={11} />Powered by 3 AI brains</p><h2>Ask anything to Claude, GPT‑4 and Gemini.</h2><span>Where independent perspectives agree, your questions become clearer.</span></div><label><span>Your question</span><textarea value={query} onChange={(event) => setQuery(event.target.value)} maxLength={500} placeholder="e.g. How can I improve my sleep quality naturally?" /></label><p className="care-section-label">Or pick a common topic</p><div className="care-topic-chips">{CARE_TOPICS.map((topic) => <button key={topic.label} onClick={() => setQuery(topic.question)}><Icon name={topic.icon} size={12} />{topic.label}</button>)}</div><button className="care-library-link" onClick={() => setView("library")}><span><Icon name="book" size={16} /></span><span><strong>Browse our health library</strong><small>Videos, articles, guides and podcasts</small></span><Icon name="chevron-right" size={15} /></button><button className="button primary wide" disabled={query.trim().length < 5} onClick={() => setView("free-result")}>Ask 3 AIs <Icon name="chevron-right" size={14} /></button><p className="result-disclaimer">Static educational demo · No live AI request is made</p></section>}
    {view === "free-result" && <section className="care-result"><div className="care-question-card"><small>Your question</small><p>“{query}”</p></div><div className="care-consensus"><div className="consensus-venn"><i>Claude</i><i>GPT‑4</i><i>Gemini</i><span><Icon name="check" size={15} />Common ground</span></div><h2>Three perspectives, one practical direction</h2><p>Start with small, consistent changes; observe the pattern over time; and seek professional guidance if the issue persists, worsens or affects daily life.</p></div><section className="profile-section"><h2>Where they agree</h2><ul className="check-list"><li><Icon name="check" size={13} />Make one sustainable change at a time.</li><li><Icon name="check" size={13} />Track what helps and what makes the concern worse.</li><li><Icon name="check" size={13} />Bring persistent or concerning changes to a clinician.</li></ul></section><section className="profile-section"><h2>Different emphasis</h2><div className="perspective-row"><span>C</span><p><strong>Claude</strong><small>Focuses on gradual habits and context.</small></p></div><div className="perspective-row"><span>G</span><p><strong>GPT‑4</strong><small>Emphasizes a repeatable plan and measurement.</small></p></div><div className="perspective-row"><span>G</span><p><strong>Gemini</strong><small>Highlights environmental and routine factors.</small></p></div></section><div className="action-list"><Link href="/doctors" className="button primary wide">Find a doctor</Link><button className="button secondary wide" onClick={() => setView("free")}>Ask another question</button></div><p className="result-disclaimer">This static comparison is educational and does not replace medical care.</p></section>}
    {view === "dashboard" && <section className="care-dashboard"><div className="care-flow-hero personalized"><p><Icon name="sparkles" size={11} />Built around your latest assessment</p><h2>Your next steps, all in one place.</h2><span>Use the roadmap, learn at your pace, or check in with your companion.</span></div><div className="case-summary"><span className="urgency-pill"><i />Medium urgency</span><h2>Headache assessment</h2><p>Most likely educational match: tension headache</p></div><div className="care-nav-cards"><button onClick={() => setView("roadmap")}><span className="violet"><Icon name="activity" size={19} /></span><span><strong>Follow your case</strong><small>See what to do now and what comes next.</small></span><b>2 of 4</b><Icon name="chevron-right" size={15} /></button><button onClick={() => setView("library")}><span className="sky"><Icon name="book" size={19} /></span><span><strong>Personalized library</strong><small>Resources selected around your care journey.</small></span><Icon name="chevron-right" size={15} /></button><button onClick={() => setView("companion")}><span className="green"><Icon name="message" size={19} /></span><span><strong>Daily companion</strong><small>Check in and organize new questions.</small></span><Icon name="chevron-right" size={15} /></button></div><Link className="button primary wide" href="/doctors?match=1">Find a matched doctor</Link></section>}
    {view === "roadmap" && <section className="care-subview"><div className="care-subview-intro"><p className="eyebrow">Your care path</p><h2>Simple steps from question to <em>follow-up.</em></h2><p>Move at your own pace. Your plan updates as your care journey changes.</p></div><div className="roadmap-list">{ROADMAP_STEPS.map((item, index) => <div key={item.title} className={item.status}><span>{item.status === "complete" ? <Icon name="check" size={13} /> : index + 1}</span><div><strong>{item.title}</strong><small>{item.detail}</small></div>{item.status === "current" && <b>Now</b>}</div>)}</div><div className="care-next-card"><Icon name="calendar" size={17} /><div><strong>Your next useful action</strong><p>Compare matched specialists and choose a visit time.</p></div><Link href="/doctors?match=1">Go</Link></div></section>}
    {view === "library" && <section className="care-subview"><div className="care-subview-intro"><p className="eyebrow">Curated education</p><h2>Learn in a way that fits your <em>moment.</em></h2><p>Short resources for understanding symptoms and preparing for care.</p></div><div className="filter-row">{["All", "Symptoms", "Appointments", "Wellness"].map((item) => <button key={item} className={filter === item ? "filter-chip selected" : "filter-chip"} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="library-list">{LIBRARY_ITEMS.filter((item) => filter === "All" || item.category === filter).map((item) => <article key={item.title}><span><Icon name={item.type === "Video" ? "video" : item.type === "Podcast" ? "microphone" : "document"} size={17} /></span><div><small>{item.type} · {item.time}</small><h3>{item.title}</h3><p>{item.category}</p></div><button aria-label={`Open ${item.title}`}><Icon name="chevron-right" size={15} /></button></article>)}</div></section>}
    {view === "companion" && <section className="care-subview companion-view"><div className="companion-avatar"><Icon name="message" size={22} /></div><h2>How are you feeling <em>today</em>?</h2><p>Your check-in is private to this session and helps organize what to watch.</p><div className="companion-options">{["A little better", "About the same", "A little worse", "I have a new question"].map((item) => <button key={item} className={companion === item ? "selected" : ""} onClick={() => setCompanion(item)}>{item}<Icon name={companion === item ? "check" : "chevron-right"} size={14} /></button>)}</div>{companion && <div className="companion-response"><Icon name="sparkles" size={15} /><div><strong>Thanks for checking in.</strong><p>{companion === "A little worse" ? "Note what changed and consider contacting a clinician if symptoms continue to worsen." : "Keep tracking meaningful changes and bring your notes to your next visit."}</p></div></div>}<button className="button secondary wide" disabled={!companion}>Add a reminder</button></section>}
  </main></FlowFrame>;
}
