import type { Doctor, DoctorSlot } from "@/types/domain";

export const DEMO_DOCTORS: Doctor[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    name: "Dr. Robert Chen",
    initials: "RC",
    specialty: "Neurology",
    subspecialty: "Headache & Migraine",
    bio: "Board-certified neurologist focused on headache disorders and migraine management, with a patient-centered approach.",
    tagline: "Has helped over 2,000 patients understand and manage their headache disorders.",
    rating: 4.9,
    reviewCount: 198,
    distanceMiles: 1.1,
    languages: ["English", "Spanish"],
    insurances: ["Aetna", "BlueCross BlueShield", "Cigna", "UnitedHealthcare"],
    locationName: "Weill Cornell Medical",
    address: "525 E 68th St, New York, NY 10065",
    boardCertified: true,
    photoUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=200&h=200&fit=crop&crop=faces",
    yearsExperience: 12,
    aiMatchScore: 97,
    videoVisit: true,
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    name: "Dr. James Morales",
    initials: "JM",
    specialty: "Internal Medicine",
    subspecialty: "Primary Care",
    bio: "Internal medicine doctor with broad experience treating common neurological symptoms in a primary care setting.",
    tagline: "Combines internal medicine with a warm, welcoming approach for patients of all ages.",
    rating: 4.7,
    reviewCount: 89,
    distanceMiles: 2.1,
    languages: ["English", "Spanish"],
    insurances: ["Aetna", "Cigna", "Humana", "Oscar Health"],
    locationName: "NYU Langone",
    address: "550 First Ave, New York, NY 10016",
    boardCertified: true,
    photoUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=200&h=200&fit=crop&crop=faces",
    yearsExperience: 8,
    aiMatchScore: 89,
    videoVisit: true,
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    name: "Dr. Sarah Patel",
    initials: "SP",
    specialty: "Neurology",
    subspecialty: "General Neurology",
    bio: "General neurologist with a decade of experience who believes hands-on examination is critical for accurate diagnosis.",
    tagline: "Patients describe her as patient, methodical and exceptionally thorough.",
    rating: 4.8,
    reviewCount: 142,
    distanceMiles: 3.4,
    languages: ["English", "Hindi"],
    insurances: ["Aetna", "BlueCross BlueShield", "Medicare"],
    locationName: "Mount Sinai Hospital",
    address: "1 Gustave L. Levy Pl, New York, NY 10029",
    boardCertified: true,
    photoUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=200&h=200&fit=crop&crop=faces",
    yearsExperience: 10,
    aiMatchScore: 84,
    videoVisit: false,
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    name: "Dr. Maria Lopez",
    initials: "ML",
    specialty: "Family Medicine",
    subspecialty: "Primary Care",
    bio: "Family medicine doctor caring for patients of all ages, with a focus on primary and pediatric care.",
    tagline: "Cares for entire families in three languages — a trusted name in primary care.",
    rating: 4.6,
    reviewCount: 64,
    distanceMiles: 4.2,
    languages: ["English", "Spanish", "Portuguese"],
    insurances: ["Cigna", "UnitedHealthcare", "Medicaid"],
    locationName: "Columbia Family Medicine",
    address: "622 W 168th St, New York, NY 10032",
    boardCertified: false,
    photoUrl: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=200&h=200&fit=crop&crop=faces",
    yearsExperience: 6,
    aiMatchScore: 78,
    videoVisit: true,
  },
  {
    id: "55555555-5555-4555-8555-555555555555",
    name: "Dr. David Kim",
    initials: "DK",
    specialty: "Neurology",
    subspecialty: "Neuromuscular Disorders",
    bio: "Senior neurologist with extensive experience treating complex neuromuscular cases.",
    tagline: "Trusted for complex cases and clear, methodical care.",
    rating: 4.9,
    reviewCount: 211,
    distanceMiles: 2.8,
    languages: ["English", "Mandarin"],
    insurances: ["BlueCross BlueShield", "Medicare", "Empire BCBS"],
    locationName: "NYU Langone — Neurology",
    address: "550 First Ave, New York, NY 10016",
    boardCertified: true,
    photoUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=200&h=200&fit=crop&crop=faces",
    yearsExperience: 15,
    aiMatchScore: 76,
    videoVisit: true,
  },
];

function futureIso(dayOffset: number, hour: number, minute: number) {
  const date = new Date();
  date.setDate(date.getDate() + dayOffset);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
}

export const DEMO_SLOTS: DoctorSlot[] = DEMO_DOCTORS.flatMap((doctor, doctorIndex) =>
  [
    { day: 1 + (doctorIndex % 2), hour: 9 + (doctorIndex % 3), minute: 30, modality: "in_person" as const },
    { day: 2 + (doctorIndex % 3), hour: 14, minute: doctorIndex % 2 ? 30 : 0, modality: "video" as const },
    { day: 4 + (doctorIndex % 2), hour: 11, minute: 30, modality: "in_person" as const },
  ].map((slot, slotIndex) => ({
    id: `${doctorIndex + 4}${slotIndex + 1}000000-0000-4000-8000-000000000000`,
    doctorId: doctor.id,
    startsAt: futureIso(slot.day, slot.hour, slot.minute),
    modality: slot.modality,
    clinicTimeZone: "America/New_York",
  })),
);
